# Generated by Django 3.0.6 on 2020-06-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_share_free_storage'),
        ('FileManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='stored_on_share',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Admin.Share'),
            preserve_default=False,
        ),
    ]
