# Generated by Django 3.0.6 on 2020-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0003_auto_20200623_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=1024),
            preserve_default=False,
        ),
    ]
