# Generated by Django 3.0.6 on 2020-06-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('FileManager', '0005_auto_20200623_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='department_vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
