# Generated by Django 3.0.6 on 2020-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0006_folder_department_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_dangling_dump',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='opened',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='opened',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
