# Generated by Django 3.0.6 on 2020-05-31 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_format', models.TextField()),
                ('metadata', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('FS', 'File Shared'), ('FC', 'File Created'), ('FE', 'File Edited'), ('FD', 'File Deleted'), ('UC', 'User Created'), ('UE', 'User Edited'), ('UD', 'User Deleted'), ('NSA', 'Network Share Added'), ('NSE', 'Network Share Edited'), ('NSR', 'Network Share Removed')], default='FC', max_length=3)),
                ('warning_level', models.CharField(choices=[('DEBU', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERR', 'Error')], default='DEBU', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField()),
                ('total_storage', models.BigIntegerField()),
                ('used_storage', models.BigIntegerField()),
            ],
        ),
    ]
