# Generated by Django 3.0.6 on 2020-06-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkShare',
            new_name='Share',
        ),
    ]
