# Generated by Django 3.0.6 on 2020-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20200609_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='address',
        ),
        migrations.AddField(
            model_name='share',
            name='directory',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
