# Generated by Django 3.0.6 on 2020-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20200609_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='free_storage',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
