# Generated by Django 3.0.6 on 2020-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_share_free_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='free_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='share',
            name='total_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='share',
            name='used_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
