# Generated by Django 3.0.6 on 2020-06-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_temporarypassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarypassword',
            name='user',
        ),
    ]
